### ISSUE TITLE
STYLE: Styling Cooking Lab

### ISSUE THREAD

**Issue by ThiiLuu79** [ThiiLuu79/cooking-lab#20]
Improving Cooking Lab's look and feel

**Comment by tien-chung** [comment]
@ThiiLuu79 Please look at the changes and let me know how you like the look and feel of the colors. Thanks!

**Comment by ThiiLuu79** [comment]
> @ThiiLuu79 Please look at the changes and let me know how you like the look and feel of the colors. Thanks!

Looks good 👍
