### ISSUE TITLE
FEAT: Create debug panel

### ISSUE THREAD

**Issue by ThiiLuu79** [ThiiLuu79/cooking-lab#26]
Debug panel for dev only.

Acceptance criterias:
- [x] Should be able to skip all the steps.
- [x] Should be able to generate a recipe.
- [x] Should be shown on local host.
- [x] Should be hidden on deployment.

**Comment by tien-chung** [comment]
@ThiiLuu79 This feature is super helpful. Thank you for thinking of this and implemented it. Great job!!
